import Head from 'next/head'
import Image from 'next/image'
import HeroSection from '../components/HeroSection'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Conference Schedule Time</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <HeroSection />
    
    </div>
  )
}
